name: CI to Docker Hub 

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
   branches:
     - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build sandbox images
        run: make all docker_org=${{ secrets.DOCKERHUB_USERNAME }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push images
        id: push_images
        run: make push docker_org=${{ secrets.DOCKERHUB_USERNAME }}
