name: Pull request verification builds

on:
  workflow_dispatch:
  pull_request:
   branches:
     - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build sandbox images
        run: make all docker_org=${{ secrets.DOCKERHUB_USERNAME }}
